google-deepmind/mujoco_mpc

- CITATION.bib
- README.md
Adds link for arXiv submission and updates CITATION.bib
> Add preprint info

- mjpc/trajectory.cc
Simplifies rollout functions `Trajectory::Rollout` and `Trajectory::RolloutDiscrete` to use `mj_step` instead of `mj_step1` and `mj_step2`.
> mj_step1 + mj_step2 -> mj_step

- mjpc/tasks/humanoid/tracking/tracking.cc
> Fix `last_key_index` in tracking residual

- mjpc/planners/ilqs/planner.cc
- mjpc/planners/ilqs/planner.h
- mjpc/tasks/hand/hand.cc
- mjpc/tasks/hand/task.xml
- Improved logic and compute inverse mapping for iLQS planner
- Actuator force cost for hand task
> Improved iLQS

- mjpc/CMakeLists.txt
- mjpc/agent.cc
- mjpc/agent.h
- mjpc/main.cc
- mjpc/task.cc
- mjpc/tasks/manipulation/common.cc
- mjpc/tasks/manipulation/common.h
- mjpc/tasks/manipulation/manipulation.cc
- mjpc/tasks/manipulation/manipulation.h
- mjpc/tasks/manipulation/merge_panda_robotiq.py
- mjpc/tasks/manipulation/task_panda_bring.xml
- mjpc/tasks/tasks.cc
- mjpc/utilities.cc
merge from deepmind branch to main
> Merge from deepmind branch to main

- mjpc/agent.cc
- mjpc/app.cc
- mjpc/main.cc
- mjpc/planners/gradient/planner.cc
- mjpc/planners/sampling/planner.cc
- mjpc/simulate.cc
- mjpc/task.cc
- mjpc/task.h
- mjpc/tasks/hand/task.xml
- mjpc/tasks/humanoid/tracking/tracking.cc
- mjpc/tasks/humanoid/tracking/tracking.h
- mjpc/tasks/manipulation/task_panda_bring.xml
- mjpc/tasks/panda/task.xml
- mjpc/tasks/particle/task.xml
- mjpc/tasks/particle/task_timevarying.xml
- mjpc/tasks/quadrotor/quadrotor.cc
- mjpc/tasks/quadrotor/quadrotor.h
- mjpc/tasks/quadruped/quadruped.cc
- mjpc/tasks/quadruped/quadruped.h
- mjpc/tasks/swimmer/task.xml
- mjpc/test/tasks/task_test.cc
- mjpc/test/testdata/particle_task.xml
- mjpc/utilities.cc
Updating with the latest internal changes.
> Updating main from deepmind

- mjpc/app.cc
- python/mujoco_mpc/agent.py
Updating the main branch with the latest changes in deepmind.
> update main from deepmind

- mjpc/app.cc
- mjpc/simulate.cc
- mjpc/simulate.h
PiperOrigin-RevId: 523963645
Change-Id: I20c014e031197bf5b80810071f93e00fb4edebe5
> Rename a few functions and variables to be a bit more Googley.

- python/mujoco_mpc/agent.py
- python/mujoco_mpc/agent_test.py
Correct Python import of gRPC classes.
> Merge deepmind->main

- mjpc/test/gradient_planner/cubic_test.cc
- mjpc/utilities.cc
Changes:
1. removed unused code in mjpc/test/gradient_planner/cubic_test.cc
2. using std::launder with reinterpret_cast in mjpc/utilities.cc
> Changes for building on Linux

- grpc/estimator_service.cc
- mjpc/estimators/buffer.h
- mjpc/estimators/estimator.cc
- mjpc/estimators/estimator.h
- mjpc/estimators/trajectory.h
- mjpc/test/estimator/estimator_force_test.cc
- python/mujoco_mpc/estimator_test.py
Modifies `Estimator::CostForce` to consider position and rotational components of forces resulting from free joints. 
Minor fix to initialization of `norm_parameters_force_`.
> Modifications to Estimator::CostForce + minor fixes

- grpc/batch_service.cc
- mjpc/estimators/batch.h
- python/mujoco_mpc/batch.py
- python/mujoco_mpc/batch_test.py
Fixes to batch estimator grpc and python interfaces to handle non-allocated dense matrices.
> Batch estimator grpc + python fixes

- mjpc/estimators/batch.cc
- mjpc/test/estimator/batch_force_test.cc
- mjpc/test/estimator/batch_optimize_test.cc
- mjpc/test/estimator/batch_prior_test.cc
- mjpc/test/estimator/batch_sensor_test.cc
- mjpc/test/testdata/estimator/particle/task1D_damped.xml
Depends on [#1034](https://github.com/deepmind/mujoco/pull/1034) fixes.
> Modifications to batch estimator for discrete inverse dynamics

- mjpc/estimators/batch.cc
- python/mujoco_mpc/batch_test.py
If sensor mask is set to false, set sensor weight to zero.
> Batch estimator sensor mask

- mjpc/estimators/batch.cc
- mjpc/estimators/batch.h
Reorder batch estimator functions and move implementations from header to source.
> Reorganize batch estimator

- grpc/batch.proto
- grpc/batch_service.cc
- mjpc/estimators/batch.cc
- mjpc/estimators/batch.h
- mjpc/test/estimator/batch_parameter_test.cc
- python/mujoco_mpc/batch.py
- python/mujoco_mpc/batch_test.py
Adds Python + gRPC support for parameter optimization to batch estimator.
Builds on #176
> Batch parameters python

- mjpc/agent.h
- mjpc/grpc/agent.proto
- mjpc/grpc/agent_service.cc
- mjpc/grpc/agent_service.h
- mjpc/planners/sampling/planner.cc
- mjpc/planners/sampling/planner.h
- mjpc/trajectory.h
- python/mujoco_mpc/agent.py
- python/mujoco_mpc/agent_test.py
This PR exposes state, action, and time trajectories from `Planner::BestTrajectory` to the Python API.
Additional minor fixes to C++.
> Best trajectory Python method

- mjpc/tasks/humanoid/stand/task.xml
> Fix subtreelinvel torso sensor

- mjpc/planners/cross_entropy/planner.h
- mjpc/planners/gradient/planner.h
- mjpc/planners/ilqg/planner.cc
- mjpc/planners/ilqg/planner.h
- mjpc/planners/ilqs/planner.h
- mjpc/planners/planner.h
- mjpc/planners/robust/robust_planner.h
- mjpc/planners/sampling/planner.h
- mjpc/simulate.cc
Adds `Planner::NumParameters` and displays the result in the GUI.
> Planner::NumParameters

- mjpc/tasks/cube/solve.cc
- mjpc/tasks/cube/solve.h
- mjpc/tasks/cube/task.xml
@erez-tom 
Added a cost term `Remaining` that depends on `goal_index_` in order to show total cost to solve state. Currently uses a fixed factor of 12. Note this factor is based on the current settings and weights. Should be sufficient for now.
> Cube solve task: Approximate remaining unscramble cost

- mjpc/agent.cc
Throw error if model is missing actuator limits. Addressing: #269.
@vikashplus
> Check model for missing actuator limits

- mjpc/direct/direct.h
- mjpc/planners/gradient/planner.h
- mjpc/planners/ilqg/planner.h
- mjpc/planners/ilqs/planner.cc
- mjpc/planners/ilqs/planner.h
> iLQS fix + planner tidy

- .github/workflows/build.yml
- mjpc/grpc/CMakeLists.txt
Use system zlib instead of building from source.
> Merge deepmind to main

- mjpc/direct/direct.cc
- mjpc/test/testdata/estimator/particle/task1D_framepos.xml
Renames "batch" in the direct optimizer to "direct".
> Rename "batch" -> "direct"
